### ISSUE TITLE
Creative Tank needing 1 Corium Tank

### ISSUE THREAD

**Issue by Discomanco** [Discomanco/Enigmatica2Expert#29]
Replace UU Matter tank with Corium Tank, because funsies.
Corium is obtained by having a Fission Reactor melt down.

Important: Information must be added to both Corium liquid, bucket and tank!

**Comment by Frikkle** [comment]
Oh I like this idea!

**Comment by Radipon** [comment]
Swapping the second essence with something from the NC salt mixer could be neat.
