### ISSUE TITLE
Remove Exchangers

### ISSUE THREAD

**Issue by Discomanco** [Discomanco/Enigmatica2Expert#34]
May already be gone from 1.80? Haven't actually checked.

Exchangers (Building Gadgets superior)
Resonant Exchanger > Creative Block Exchanger

**Comment by Frikkle** [comment]
Weren't the Exchangers recipes tweaked to be a bit more of a pain to make? If so, shouldn't the building gadget ones be as well? (Would be silly since these are building utilities and they do not help you to more easily complete the pack)

**Comment by Discomanco** [comment]
Mmm nope, seems like they are just a pain in general to craft :P

**Comment by Discomanco** [comment]
And the fact that it has already been removed in the latest versions, so there's that :P

**Comment by Frikkle** [comment]
I love mods that have that built-in
