### ISSUE TITLE
Remove Animania?

### ISSUE THREAD

**Issue by Discomanco** [Discomanco/Enigmatica2Expert#37]
In the end, doesn't do much, and big animal farms has a tendency to bring TPS to its knees.
For Cosmic Meatballs, lots of meat-related food from Pams could be added

**Comment by NielsPilgaard** [comment]
I think it should be removed, way too hard a performance hit without adding much. I think the Cosmic Meatball recipe is tedious anyhow, not very interesting.

**Comment by AmyMialee** [comment]
I think the only time I've used Animania is for early game food and more hearts, really not a fan of that mod.
