### ISSUE TITLE
Remove Block Drops

### ISSUE THREAD

**Issue by NielsPilgaard** [Discomanco/Enigmatica2Expert#43]
The mod that displays block drops in JEI increases load time a lot, I've been told. I think you/we/someone should investigate how much of a different it makes.

**Comment by theboo** [comment]
If you are talking about forge loading, i just tested 3 times with block drops mod enabled and then 3 times with block drops mod disabled using e2e 1.80. All 6 tests came to exactly 5 minutes and 4 seconds lol... if you really want to save time, watching the loading happen i can tell u removing jei(and all the jei addons), CT and thaumcraft will save about 2 minutes and 30 seconds xD..

Testing done on my laptop which has an i7- 9750H and 8gb ram allocated to minecraft.

**Comment by NielsPilgaard** [comment]
It only increases load time if the item registry has changed in some way.
